# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
a = 2.0 + 3.0/5.0
b = (a+10.2)-5.0*2.0
c = a/b + 33.8
d = a/(b+c)
e = d*2
var = [a, b, c, d, e]
for x in var:
    print (x)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [2]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_b = lista_a*2
lista_c = lista_a + lista_b
print(lista_a)
print(lista_b)
print(lista_c)

[2.0, 3.0, 5.0, 10, 20, 30]
[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [7]:
lista_d = lista_a/(lista_b*lista_c)

TypeError: can't multiply sequence by non-int of type 'list'

As três primeiras operações deram certo uma vez que a soma e multiplicação (esta última, desde que feita utilizando números inteiros) em listas resulta na concatenação desta classe de objetos. A soma adiciona os elementos em sequência, enquanto a multiplicação repete os valores contidos na lista. Contudo, a lista_d não é possível por conta das características de lista ao utilizar operadores aritméticos, como demonstrado a seguir:

In [ ]:
lista_demonstracao_erro_1 = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]*[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

TypeError: can't multiply sequence by non-int of type 'list'

Como mostrado no código acima (que nada mais seria que lista_b*lista_c), a multiplicação só pode ser feita com números inteiros, uma vez que em lista não é a multiplicação de cada valor contido internamente, mas sim a repetição dos elementos.

In [ ]:
lista_demonstracao_erro_2 = lista_a*2.0

TypeError: can't multiply sequence by non-int of type 'float'

De mesmo modo, a substituição de um número inteiro por um float, mesmo que numericamente sejam iguais (exemplo: 2 e 2.0), também resulta em um erro.

In [ ]:
lista_demonstracao_erro_3 = lista_a/lista_b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
lista_demonstracao_erro_4 = lista_a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Por fim, pela mesma razão que não é a multiplicação dos valores e sim a repetição concatenando os valores, também não é possível fazer a divisão de listas. Neste caso, mesmo que utilize valores inteiros não funcionará o código, uma vez que a operação de divisão não é suportada para a classe.

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [3]:
lista_1 = [a, b, c, d, e]
lista_2 = [a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista_3 = lista_1 + lista_2
lista_3

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [4]:
import numpy as np
import pandas as pd

In [5]:
lista_duplicada = lista_3*2
lista_array = np.array(lista_duplicada).reshape(5,4)
lista_array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [6]:
media_colunas = []
x = 0
while x < 4:
    media_colunas.append(float(np.mean(lista_array[:,x]))),
    x=x+1
media_colunas

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [7]:
lista_array = np.array(lista_duplicada).reshape(5,4)

# 1 - usando shape no array do exercício 4
print("Tamanho inicial da matriz =", lista_array.shape)

# 2 - Adicionando as médias das colunas
lista_array = np.append(lista_array, media_colunas)

# 3 - Recupere e exiba o array resultante
lista_array

Tamanho inicial da matriz = (5, 4)

array([ 2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796,
        2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
        1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796,
        7.88073291,  2.14941306,  7.88073291,  2.14941306])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [8]:
# Remodelando o array para ter 4 colunas
lista_array = lista_array.reshape(-1,4)
lista_array
# Convertendo array para DataFrame
df = pd.DataFrame(lista_array)
# Arredondando valores para até 3 casas decimais
df = round(df, 3)

df

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

In [9]:
# ou, alternativamente, convertendo array para DataFrame e arredondando valores direto
df = round(pd.DataFrame(lista_array), 3)
df

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [10]:
df = round(pd.DataFrame(lista_array), 3)

# Média das linhas
media_linhas = df.mean(axis=1)
media_linhas = round(media_linhas, 3)
df = pd.concat([df, media_linhas], axis = 1, ignore_index=True)
df

        0      1       2      3       4
0   2.600  2.800  34.729  0.069  10.050
1   0.139  1.612   1.673  5.893   2.329
2   0.263  0.372   2.600  2.800   1.509
3  34.729  0.069   0.139  1.612   9.137
4   1.673  5.893   0.263  0.372   2.050
5   7.881  2.149   7.881  2.149   5.015

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [11]:
print("describe() linhas:")
print(df.iloc[5,:].describe())
print()
print("describe() colunas:")
print(df.iloc[:,4].describe())

describe() linhas:
count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

describe() colunas:
count     6.000000
mean      5.015000
std       3.758722
min       1.509000
25%       2.119750
50%       3.672000
75%       8.106500
max      10.050000
Name: 4, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [12]:
df.rename(
    columns = {4:"Média Linhas"},
    index = {5:"Média Colunas"},
    inplace = True
)
print(df)
print()
print("Média das Médias:")
print("Forma 1 =", df.mean().mean())
print("Forma 2 =", df.iloc[5, 4])
print("Forma 3 =", df.iloc[-1,-1])
print("Forma 4 =", df.loc['Média Colunas', 'Média Linhas'])

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149         5.015

Média das Médias:
Forma 1 = 5.015000000000001
Forma 2 = 5.015
Forma 3 = 5.015
Forma 4 = 5.015