# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [7]:
a = 2.0+3.0/5.0 == 10
b = (a+10.2)-5.0*2.0 <= 2.9
c = 10 <= a/b+33.8 < 100
d = 5 != a/(b+c)
e = 33 == d*2
print("Resultados:")
print(a)
print(b)
print(c)
print(d)
print(e)

Resultados:
False
True
True
True
False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [34]:
print("Relação original 1:")
print(('a',1,True,'b',0,False) != ('a',True,1,'b',False,0))
print("Substituindo por == resulta em:")
print(('a',1,True,'b',0,False) == ('a',True,1,'b',False,0))
print()

print("Relação original 2:")
print(['a',1,True,'b',0,False] != ('a',True,1,'b',False,0))
print("Substituindo por == resulta em:")
print(['a',1,True,'b',0,False] == ('a',True,1,'b',False,0))
print()

print("Relação original 3:")
print(['a',1,True,'b',0,False] != ['a',True,1,'b',False,0])
print("Substituindo por == resulta em:")
print(['a',1,True,'b',0,False] == ['a',True,1,'b',False,0])
print()

print("Relação original 4:")
print(['a',1,True,'b',0,False] > ['a',True,1])
print("Substituindo por < resulta em:")
print(['a',1,True,'b',0,False] < ['a',True,1])
print()

print("Relação original 5:")
print(['a',1,True,'b',0,False] == 1)
print("Substituindo por != resulta em:")
print(['a',1,True,'b',0,False] != 1)
print()

print("Relação original 6:")
print(['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False])
print("Substituindo <= por < resulta em:")
print(['a',True,1] < ['a',True,1] < ['a',1,True,'b',0,False])

Relação original 1:
False
Substituindo por == resulta em:
True

Relação original 2:
True
Substituindo por == resulta em:
False

Relação original 3:
False
Substituindo por == resulta em:
True

Relação original 4:
True
Substituindo por < resulta em:
False

Relação original 5:
False
Substituindo por != resulta em:
True

Relação original 6:
True
Substituindo <= por < resulta em:
False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [36]:
import pandas as pd
import numpy as np

In [38]:
# Recuperando o objeto criado anteriormente

# Variáveis iniciais
a = 2.0 + 3.0/5.0
b = (a+10.2)-5.0*2.0
c = a/b + 33.8
d = a/(b+c)
e = d*2

# Transformando em array
lista_1 = [a, b, c, d, e]
lista_2 = [a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista_3 = lista_1 + lista_2
lista_duplicada = lista_3*2
lista_array = np.array(lista_duplicada).reshape(5,4)

# Adicionando a média das colunas
media_colunas = []
x = 0
while x < 4:
    media_colunas.append(float(np.mean(lista_array[:,x]))),
    x=x+1
media_colunas
lista_array = np.append(lista_array, media_colunas)

# Transformando em DataFrame
lista_array = lista_array.reshape(-1,4)
df = round(pd.DataFrame(lista_array), 3)

# Adicionando a média das linhas
media_linhas = df.mean(axis=1)
media_linhas = round(media_linhas, 3)
df = pd.concat([df, media_linhas], axis = 1, ignore_index=True)

# Renomeando
df.rename(
    columns = {4:"Média Linhas"},
    index = {5:"Média Colunas"},
    inplace = True
)

df

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149         5.015

In [39]:
df.to_csv('nome_do_arquivo.csv')

In [50]:
df_2 = pd.read_csv('nome_do_arquivo.csv', index_col='Unnamed: 0').round(3)
df_2

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149         5.015

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [67]:
array_ones = np.ones_like(df_2)
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [ ]:
# Como false é igual a 0 e true igual a 1, a soma das linhas e colunas (.sum().sum())
# resulta na quantidade de verdadeiros

(df_2 == array_ones).sum().sum()

# Nesse caso, nenhum valor é igual, portanto; a soma é 0 (tudo = False)

np.int64(0)

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [89]:
# Mesma lógica. Se os valores da DataFrame forem superiores receberão True = 1), e se inferiores ou iguais
# receberão False = 0. Logo, as somas de 1 (True) resulta em quantos valores são superiores ao array.
(df_2 > array_ones).sum().sum()

np.int64(22)

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [ ]:
# Considerando que os valores inferiores ou iguais devem compor o resto dos superiores calculados
# no anterior, a soma de ambos os resultados deve ser igual ao total de valores existentes.
# Neste caso, 30, uma vez que a forma é de 6x5.
(df_2 <= array_ones).sum().sum()

np.int64(8)

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [172]:
(df_2.gt(0) & df_2.lt(1)).sum().sum()

np.int64(8)

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [251]:
# Primeira forma possível
lista_df_2 = df_2.iloc[:,4].to_numpy().tolist()
lista_df_2
x = 0
lista_menor_igual_5 = []
while x < len(lista_df_2):
    lista_menor_igual_5.append(lista_df_2[x]<=5)
    x = x+1
lista_menor_igual_5.count(True)

3

In [249]:
# Segunda forma possível
lista_df_2 = list(df_2.values.transpose())
(lista_df_2[4]<=5).sum().sum()

np.int64(3)

In [247]:
# Terceira forma possível
lista_df_2 = list(df_2.iloc[:,4])
x = 0
lista_menor_igual_5 = []
while x < len(lista_df_2):
    lista_menor_igual_5.append(lista_df_2[x]<=5)
    x = x+1
lista_menor_igual_5.count(True)

3

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [228]:
print(df_2)

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149         5.015

In [245]:
# Primeira forma possível
lista_2_df_2 = list(df_2.values)
(lista_2_df_2[5]>5).sum().sum()

np.int64(3)

In [244]:
# Segunda forma possível
lista_2_df_2 = list(df_2.iloc[5,:])
x=0
lista_maior_5 = []
while x < len(lista_2_df_2):
    lista_maior_5.append(lista_2_df_2[x]>5)
    x = x+1
lista_maior_5.count(True)

3