# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [131]:
p = 2.0+3.0/5.0==10
q = (p+10.2)-5.0*2.0<=2.9
r = 10 <= p/q + 33.8 < 100
s = 5 != p/(q+r)
t = 33 == s*2

print("Resultado 'p and q and r and s and t':")
print(p and q and r and s and t)
print()
print("Algumas possibilidades para inverter o resultado:")
print("Substituindo o primeiro e último 'and' por 'or' =", p or q and r and s or t)
# Uma vez que 'and' ambos tem que ser True, mas o primeiro e último objeto são False
# Trocando para 'or', apenas um tem que ser True, nesse caso, o segundo e quarto objeto
print("Substituindo 'and' por 'and not' e trocando a ordem de p e q =", q and not p and r and s and not t)
# And not precisa que o primeiro seja True e o segundo False
# Funciona diretamente para s (True) e t (False), mas para p (False) e q (True) é necessário trocar a ordem

Resultado 'p and q and r and s and t':
False

Algumas possibilidades para inverter o resultado:
Substituindo o primeiro e último 'and' por 'or' = True
Substituindo 'and' por 'and not' e trocando a ordem de p e q = True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [132]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print("Usando apenas o operador or:")
print("p or q or r or s or t or u =", p or q or r or s or t or u)
print()
print("É necessário colocar 'or not' na relação p-q, r-s, t-u:")
print("p or not q or r or not s or t or not u =",p or not q or r or not s or t or not u)
# Para trocar True por False, 'or not' precisa ter uma relação 'False or not True'
# Dessa forma, p (False) e q (True), r (False) e s (True), t (False) e u (True)
# É necessário trocar todas essas relações e não apenas uma,
# uma vez que para "or" apenas uma relação True faz com que toda a relação seja True

Usando apenas o operador or:
p or q or r or s or t or u = True

É necessário colocar 'or not' na relação p-q, r-s, t-u:
p or not q or r or not s or t or not u = False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [34]:
import pandas as pd
import numpy as np

In [133]:
df = pd.read_csv('nome_do_arquivo.csv', index_col='Unnamed: 0').round(3)
print(df)
print()

print("A segunda linha é igual a terceira ou a terceira linha é igual a quarta?")
print(np.any((df.iloc[1,:] == df.iloc[2,:], df.iloc[2,:] == df.iloc[3,:])))

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149         5.015

A segunda linha é igual a terceira ou a terceira linha é igual a quarta?
False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [134]:
print(np.all(df.iloc[0,:]>=10))

False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [135]:
print(np.all((df.iloc[:,2] >= 0, df.iloc[:,2] <40)))

True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [136]:
print(np.any(df.iloc[5,:]>10))

False

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [137]:
df_2 = df[(df>5) & (df<7)]
df_2

                0      1   2      3  Média Linhas
0             NaN    NaN NaN    NaN           NaN
1             NaN    NaN NaN  5.893           NaN
2             NaN    NaN NaN    NaN           NaN
3             NaN    NaN NaN    NaN           NaN
4             NaN  5.893 NaN    NaN           NaN
Média Colunas NaN    NaN NaN    NaN         5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [138]:
df_3 = df[(df<=5) | (df>7)]
df_3

                    0      1       2      3  Média Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673    NaN         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673    NaN   0.263  0.372         2.050
Média Colunas   7.881  2.149   7.881  2.149           NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [139]:
array_1 = df.iloc[:,3].to_numpy()
array_2 = df.iloc[:,4].to_numpy()
print("Primeiro array (penúltima coluna):")
print(array_1)
print()
print("Segundo array (última coluna):")
print(array_2)
print()
print("Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?")
print(np.any((array_1 >= 2) & (array_1 <= 5)))

Primeiro array (penúltima coluna):
[0.069 5.893 2.8   1.612 0.372 2.149]

Segundo array (última coluna):
[10.05   2.329  1.509  9.137  2.05   5.015]

Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?
True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [140]:
print(np.all(((array_1>-1) & (array_1<12) & (array_2>-1) & (array_2<12))))

True